on: 
   issues:
    types: [opened]
   push:
    branches:
      - main
   pull_request:
    branches:
      - main

jobs:
  artia_comment_job:
    runs-on: ubuntu-latest
    name: A job to comment in artia activity.
    steps:
      - name: Ste
        id: hello
        uses: donPain/action_temp@v1.36
        with: 
          organizationId: 111402
          accountId: 3757321
          creatorEmail: 'nerdplis@gmail.com'
          creatorPassword: ${{ secrets.ARTIA_PASSWORD }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"



